---
- hosts: localhost
  connection: local
  # become: yes
  # become_method: sudo
  pre_tasks:
   - include: tasks/enable-repositories.yml
  tasks:
   - include: tasks/update.yml
   - include: tasks/packages.yml
     
