---
- hosts: localhost
  vars:
    ansible_connection: local
  pre_tasks:
   - name: Update system
     dnf: 
      name: "*"
      state: latest
  tasks:
   - include: tasks/packages.yml
  post_tasks:
   - name: Reboot
     reboot: 
