---
- hosts: localhost
  connection: local
  become: yes
  become_user: root
  pre_tasks:
   - name: Update system
     dnf: 
      name: "*"
      state: latest
  tasks:
   - include: tasks/packages.yml
  post_tasks:
   - name: Reboot
     reboot: 
     
